version: 1
disable_existing_loggers: false

formatters:
  structured:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/clarity.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  mania_risk:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/mania_risk.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  clarity.ml.mania_risk_analyzer:
    level: INFO
    handlers: [console, mania_risk]
    propagate: false
  
  clarity:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: WARNING
  handlers: [console]