name: Lint

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run ruff
      run: |
        echo "::group::Ruff Linting"
        ruff check . --output-format=github
        echo "::endgroup::"
    
    - name: Run mypy
      run: |
        echo "::group::MyPy Type Checking"
        mypy src/clarity/ --strict
        echo "::endgroup::"
    
    - name: Run bandit security check
      run: |
        echo "::group::Bandit Security Check"
        bandit -r src/ -f json -o bandit-report.json || true
        python -c "import json; report=json.load(open('bandit-report.json')); print(f'Found {len(report[\"results\"])} security issues')"
        echo "::endgroup::"
    
    - name: Check for lint regression
      run: |
        # Baseline lint error count (update as we improve)
        BASELINE_ERRORS=947
        
        # Count current errors
        CURRENT_ERRORS=$(ruff check . 2>&1 | grep "Found" | awk '{print $2}' || echo "0")
        
        echo "Baseline errors: $BASELINE_ERRORS"
        echo "Current errors: $CURRENT_ERRORS"
        
        if [ "$CURRENT_ERRORS" -gt "$BASELINE_ERRORS" ]; then
          echo "❌ Lint regression detected! Current errors ($CURRENT_ERRORS) exceed baseline ($BASELINE_ERRORS)"
          exit 1
        else
          echo "✅ No lint regression. Current errors ($CURRENT_ERRORS) within baseline ($BASELINE_ERRORS)"
        fi
    
    - name: Upload lint results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint-results
        path: |
          bandit-report.json